.TH CLIPB "1" "2023" "NNB" "User Commands"
.SH NAME
cb \- Clipboard managers warper
.SH SYNOPSIS
.B cb
.TP
.B cb STRING
.TP
.B echo STRING | cb
.TP
.B cb < file.txt
.TP
.B cb | other-tool
.SH DESCRIPTION
cb is a clipboard managers warper written in POSIX sh that wraps various system-specific tools for interacting with a system clipboard.
.SH REPORTING BUGS
Report bugs to https://codeberg.org/NNB/cb/issues
